In [664]:
import pandas as pd
import re

In [665]:
pd.set_option('display.max_columns', None)
pd.set_option('max_colwidth', None)
hkp_data = pd.read_csv('hkp.csv')
hkp_data['misc'] = hkp_data.misc.fillna('N')

In [666]:
[{'id': 'FM12', 'name': 'Clubhouse'}, {'id': 'FM02', 'name': 'Swimming Pool'}, {'id': 'FM01', 'name': "Kids' Facilities"}, {'id': 'FM10', 'name': 'Sports Facilities'}, {'id': 'FM14', 'name': 'Mall'}]

[{'id': 'FM12', 'name': 'Clubhouse'},
 {'id': 'FM02', 'name': 'Swimming Pool'},
 {'id': 'FM01', 'name': "Kids' Facilities"},
 {'id': 'FM10', 'name': 'Sports Facilities'},
 {'id': 'FM14', 'name': 'Mall'}]

In [667]:
len(hkp_data.misc)

9900

In [668]:
list_of_key = []
for j in range(1,len(hkp_data.misc)):
    for i in hkp_data.misc[j].split('{'):
        if len(i) > 1:
            list_of_key.append(re.search(r"([A-z])\w+",i.split(':')[-1]).group(0))

In [669]:
for i in list(set(list_of_key)):
    hkp_data[i] = ""

In [670]:
list_of_key = []
for j in range(1,len(hkp_data.misc)):
    diction = []
    for i in hkp_data.misc[j].split('{'):
        if len(i) > 1:
            diction.append(re.search(r"([A-z])\w+",i.split(':')[-1]).group(0))
    list_of_key.append(diction)

In [671]:
list_of_facility = []
hkp_data['facility'] = hkp_data.facility.fillna('N')
for j in range(1,len(hkp_data.facility)):
    for i in hkp_data.facility[j].split('{'):
        if len(i) > 1:
            list_of_facility.append(re.search(r"([A-z])\w+",i.split(':')[-1]).group(0))
facility_unique = list(set(list_of_facility))
facility_unique.remove('Clubhouse')
facility_unique.remove('Swimming')
for i in list(set(facility_unique)):
    hkp_data[i] = ""

In [672]:
list_of_facility = []
for j in range(1,len(hkp_data.facility)):
    diction = []
    for i in hkp_data.facility[j].split('{'):
        if len(i) > 1:
            diction.append(re.search(r"([A-z])\w+",i.split(':')[-1]).group(0))
    list_of_facility.append(diction)

In [673]:
counter = 0 
for i in list_of_key:
    for key in i:
        hkp_data.loc[counter,key] = 1
    counter += 1

In [674]:
counter = 0 
for i in list_of_facility:
    for key in i:
        hkp_data.loc[counter,key] = 1
    counter += 1

In [675]:
to_drop_hkp = ['misc', 'facility',
       'Studio','Key','Health','Disneyland',
       'Racecourse',
       'Master', 'Basic','Appliances', 'Duplex',
       'Pet', 'Private', 'Adjacent',
       'Catering', 'Golf', 'Sports', 'Kids','Entertainment','Recreational','Original']

In [676]:
hkp_data = hkp_data.drop(columns = to_drop_hkp)

,Unnamed: 0,price,floor_level,bedroom_amount,net_area,district,address,url_desc,Mountain,Balcony,Roof,Car,Terrace,River,Close,Sea,Garden,Newly,Swimming,Garage,Clubhouse,Well,Mall
2764,2764,12800000,L,NaN,677,Shatin,1 Mei Tin Road,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Festival-City-Phase-1-Block-2-Low-Floor-Flat-NA-H300176363,,,,,,,,,,,,,,,
3330,3330,8000000,H,3.0,451,Shatin,3 Hang Shing Street,https://www.hkp.com.hk/en/property/New-Territories-Shatin-City-One-Shatin-Phase-3-Block-30-High-Floor-Flat-F-H300212686,,,,,,,,,,,,,,,
3769,3769,0,M,NaN,443,Shatin,69 Che Kung Miu Road,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Hin-Keng-Estate-Hin-Yau-House-Middle-Floor-Flat-10-H300168471,,,,,,,,,,,,,,,
4257,4257,7780000,M,3.0,560,Shatin,52 Tai Chung Kiu Road,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Belair-Gardens-Block-N-Nelly-Height-Middle-Floor-Flat-C-H300207051,,,,,,,,,,,,,,,
4955,4955,4080000,H,3.0,215,Shatin,7-11 Sha Kok Street,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Greenwood-Garden-Block-B-High-Floor-Flat-4-H300201796,,,,,,,,,,,,,,,
5348,5348,12300000,M,3.0,817,Shatin,18 Pak Lok Path,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Pristine-Villa-Block-13-Middle-Floor-Flat-D-H300199617,,1,,,,,,,,,1,,1,,
5933,5933,6800000,H,2.0,347,Shatin,2-16 Wang Pok Street,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Shatin-Centre-Block-D-Tong-Ning-Building-High-Floor-Flat-C-H300194273,,1,,,,,,,,,1,,,,
6495,6495,10800000,M,3.0,707,Shatin,1 Po Shing Street,https://www.hkp.com.hk/en/property/New-Territories-Shatin-City-One-Shatin-Phase-7-Block-35-Middle-Floor-Flat-B-H300187368,,,,,,,,,,,,,,,
7418,7418,4900000,L,1.0,297,Shatin,11-17 Sha Tin Centre Street,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Wai-Wah-Centre-Block-4-Low-Floor-Flat-G-H300215595,,1,,,,,,1,,,1,,1,,
7423,7423,3700000,L,NaN,242,Shatin,20-30 Tai Chung Kiu Road,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Garden-Rivera-Block-B-Low-Floor-Flat-7-H300215501,,,,,,,,,,,,,,,
7491,7491,0,M,NaN,443,Shatin,69 Che Kung Miu Road,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Hin-Keng-Estate-Hin-Kwai-House-Middle-Floor-Flat-18-H300214593,,,,,,,,,,,1,,1,,
7520,7520,3400000,L,3.0,215,Shatin,7-11 Sha Kok Street,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Greenwood-Garden-Block-B-Low-Floor-Flat-8-H300214262,,,,,,,,,,,1,,,,
7521,7521,4050000,M,3.0,271,Shatin,7-11 Sha Kok Street,https://www.hkp.com.hk/en/property/New-Territories-Shatin-Greenwood-Garden-Block-C-Middle-Floor-Flat-2-H300214263,,,,,,,,,,,,,,,

In [677]:
hkp_data['location'] = ''
counter = 0

hkp_district = []
for i in hkp_data['district']:
    helper = i.split(' / ')
    hkp_district.append(helper)
counter = 0  
for i in hkp_district:
    if len(i) > 1:
        hkp_data.loc[counter,'location'] = i[1]
    else:
        hkp_data.loc[counter,'location'] = i[0] 
    counter +=1

In [678]:
def hkp_floor(listV2,column,value):
    counter = 0
    for i in hkp_data[listV2]:
        if i ==1:
            hkp_data.loc[counter,column] = value
        counter += 1

In [679]:
hkp_data['car_parking'] = ''
for i in ['Garage','Car']:
    hkp_floor(i,'car_parking',1)
hkp_data = hkp_data.drop(columns=['Garage','Car'])
hkp_data = hkp_data.drop(columns=['Unnamed: 0','district'])

In [680]:
hkp_data['Lux_Revo'] = ''
for i in ['Newly','Well']:
    hkp_floor(i,'Lux_Revo','1')
hkp_data=hkp_data.drop(columns=['Newly','Well'])

In [681]:
hkp_data['price_per'] = round(hkp_data['price']/hkp_data['net_area'])

In [682]:
hkp_data = hkp_data.rename(columns={'River':'River View','Sea':'Sea View','Garden':'Garden View','Clubhouse':'Club House',
                                   'Close':'MTR nearby','Mountain':'Mountain View','Mall':'Shopping Mall nearby',
                                   'Roof':'Rooftop','url_desc':'link'})

In [683]:
hkp_data['building'] = ''

In [684]:
hkp_data=hkp_data.reindex(sorted(hkp_data.columns), axis=1)

In [686]:
hkp_data

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,address,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
0,1,1,,,,,,,,,1,,89 Pok Fu Lam Road,2.0,,,H,https://www.hkp.com.hk/en/property/Hong-Kong-Island-Hong-Kong-West-The-Belcher-s-Phase-1-Block-1-High-Floor-Flat-B-H100203780,Hong Kong West,766,20200000,26371.0
1,,1,,,,,,,,,,,1 Sheung Foo Street,2.0,,,NaN,https://www.hkp.com.hk/en/property/Kowloon-Ho-Man-Tin-One-Homantin-Tower-2-Flat-D-H200090728,Ho Man Tin,493,11000000,22312.0
2,,,,,,,,1,,,,,9 Carmel Village Street,2.0,,1,M,https://www.hkp.com.hk/en/property/Kowloon-Ho-Man-Tin-Carmel-On-The-Hill-Middle-Floor-Flat-C-H200061503,Ho Man Tin,482,9500000,19710.0
3,1,1,,,,,,,,,1,,34G Braga Circuit,3.0,,,NaN,https://www.hkp.com.hk/en/property/Kowloon-Ho-Man-Tin-34G-Braga-Circuit-H200058073,Ho Man Tin,1485,38000000,25589.0
4,1,1,,,,,,,,,1,,3 Julia Avenue,2.0,,,NaN,https://www.hkp.com.hk/en/property/Kowloon-Ho-Man-Tin-3-Julia-Avenue-Julia-Avenue-3-Flat-C-H200077126,Ho Man Tin,656,14000000,21341.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9895,,,,,,,,,,,,,9 Tong Yin Street,NaN,,,H,https://www.hkp.com.hk/en/property/Kowloon-Tseung-Kwan-O-Town-Centre-The-Wings-Phase-1-Tower-6-Sun-Diamond-High-Floor-Flat-E-H200188082,Tseung Kwan O Town Centre,538,10400000,19331.0
9896,,,,,,,,,,1,,,9-23 Sui Man Road,NaN,,,NaN,https://www.hkp.com.hk/en/property/Hong-Kong-Island-Shau-Kei-Wan-Chai-Wan-Moon-Wah-Building-Flat-11-H100188952,Chai Wan,322,4400000,13665.0
9897,1,,1,,,,,,,,1,,863 Lai Chi Kok Road,NaN,,,H,https://www.hkp.com.hk/en/property/Kowloon-Lai-Chi-Kok-Banyan-Garden-Phase-III-Block-6-High-Floor-Flat-B-H200065527,Lai Chi Kok,511,9280000,18160.0
9898,,1,,,,,,,,,,,7 Mount Sterling Mall,3.0,,,H,https://www.hkp.com.hk/en/property/Kowloon-Mei-Foo-Mei-Foo-Sun-Chuen-Phase-VII-No-7-Mount-Sterling-Mall-High-Floor-Flat-D-H200026830,Mei Foo,748,9800000,13102.0
9899,,,,,,,,,,,,,88 Po Hong Road,NaN,,,L,https://www.hkp.com.hk/en/property/Kowloon-Po-Lam-Serenity-Place-Block-4-Low-Floor-Flat-E-H200129291,Po Lam,604,7300000,12086.0

# MID LIFE

In [687]:
Mid_life = pd.read_csv('Mid_life.csv')
Mid_life['misc'] = Mid_life.misc.fillna('N')

In [688]:
list_of_key = []
for j in range(1,len(Mid_life.misc)):
    diction = []
    for i in Mid_life.misc[j].split('{'):
        if len(i) > 1:
            diction.append(re.search(r"([A-z])\w+",i.split(':')[-1]).group(0))
    list_of_key.append(diction)

In [689]:
list_of_key_Midife = []
for i in list_of_key:
    for j in i:
        list_of_key_Midife.append(j)
        
for i in list(set(list_of_key_Midife)):
    Mid_life[i] = ""

In [690]:
list_of_facility = []
Mid_life['facility'] = Mid_life.facility.fillna('N')
for j in range(1,len(Mid_life.facility)):
    for i in Mid_life.facility[j].split('{'):
        if len(i) > 1:
            list_of_facility.append(re.search(r"([A-z])\w+",i.split(':')[-1]).group(0))
facility_unique = list(set(list_of_facility))
facility_unique.remove('Clubhouse')
facility_unique.remove('Swimming')
for i in list(set(facility_unique)):
    Mid_life[i] = ""

In [691]:
list_of_facility = []
for j in range(1,len(Mid_life.facility)):
    diction = []
    for i in Mid_life.facility[j].split('{'):
        if len(i) > 1:
            diction.append(re.search(r"([A-z])\w+",i.split(':')[-1]).group(0))
    list_of_facility.append(diction)

In [692]:
counter = 0 
for i in list_of_key:
    for key in i:
        Mid_life.loc[counter,key] = 1
    counter += 1

In [693]:
counter = 0 
for i in list_of_facility:
    for key in i:
        Mid_life.loc[counter,key] = 1
    counter += 1

In [694]:
Mid_life['location'] = ''
counter = 0

Mid_life_district = []
for i in Mid_life['district']:
    helper = i.split(' / ')
    Mid_life_district.append(helper)
counter = 0  
for i in Mid_life_district:
    if len(i) > 1:
        Mid_life.loc[counter,'location'] = i[1]
    else:
        Mid_life.loc[counter,'location'] = i[0] 
    counter +=1

In [695]:
def Mid_life_floor(listV2,column,value):
    counter = 0
    for i in Mid_life[listV2]:
        if i ==1:
            Mid_life.loc[counter,column] = value
        counter += 1

In [696]:
Mid_life['Lux_Revo'] = ''
for i in ['Newly','Well']:
    Mid_life_floor(i,'Lux_Revo','1')
Mid_life=Mid_life.drop(columns=['Newly','Well'])

In [697]:
Mid_life['car_parking'] = ''
for i in ['Garage','Car']:
    Mid_life_floor(i,'car_parking',1)
Mid_life = Mid_life.drop(columns=['Garage','Car'])
Mid_life = Mid_life.drop(columns=['Unnamed: 0','district'])

In [698]:
to_drop_Mid_life = ['misc', 'facility',
       'Racecourse',
       'Duplex', 'Pet', 'Adjacent', 'Recreational', 'Health', 'Catering',
       'Golf', 'Sports', 'Kids', 'Entertainment', 'Key' ]

In [699]:
Mid_life = Mid_life.drop(columns = to_drop_Mid_life)

In [700]:
Mid_life = Mid_life.rename(columns={'River':'River View','Sea':'Sea View','Garden':'Garden View','Clubhouse':'Club House',
                                   'Close':'MTR nearby','Mountain':'Mountain View','Mall':'Shopping Mall nearby',
                                   'Roof':'Rooftop','url_desc':'link'})

In [701]:
Mid_life['building'] = ''

In [702]:
Mid_life['price_per'] = round(Mid_life['price']/Mid_life['net_area'])
Mid_life=Mid_life.reindex(sorted(Mid_life.columns), axis=1)

# SquareFoot

In [703]:
squarefoot = pd.read_csv('test.csv')
squarefoot[squarefoot.price_per.isnull()]

,area,link,location,price,price_per,tags
145,"\n (Gross: 2,100 ft²) \n",https://www.squarefoot.com.hk/buy/residential/property-32065,"\n Tai Po\n ,\n Village\n",HKD$12.5 Millions,NaN,"\n ,\n \n \n\n ,\n ,House,Village House,Garden,Balcony,RoofTop,Sea view,\n"
382,"\n (Gross: 435 ft²), 1 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-30172,"\n Clear Water Bay\n ,\n Village House\n",HKD$4.6 Millions,NaN,"\n ,\n \n \n\n ,\n ,Village House,Mountain view,Good view,Simple,RoofTop"
555,"\n (Gross: 700 ft²), 2 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-27207,"\n Sai Kung\n ,\n Village\n",HKD$5 Millions,NaN,"\n ,\n \n \n\n ,\n ,Village House,Good view,Simple,Balcony"
559,"\n (Gross: 650 ft²), 3 beds , 2 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-27198,"\n Clear Water Bay\n ,\n Village House\n",HKD$7.5 Millions,NaN,"\n ,\n \n \n\n ,\n ,Village House,Elegant,Garden,Ensuite"
560,"\n (Gross: 1,400 ft²) \n",https://www.squarefoot.com.hk/buy/residential/property-27196,"\n Clear Water Bay\n ,\n Village House\n",HKD$16 Millions,NaN,"\n ,\n \n \n\n ,\n ,Village House,Sea view,Elegant,Balcony,RoofTop,Ensuite"
...,...,...,...,...,...,...
5822,"\n (Gross: 10,923 ft²) \n",https://www.squarefoot.com.hk/buy/residential/property-32818,"\n Kowloon Tong\n ,\n House\n",HKD$300 Millions,NaN,"\n ,\n \n \n\n ,\n ,House,With tenant agreement,Good school zone"
5874,"\n (Gross: 700 ft²), 2 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-12994,"\n Clear Water Bay\n ,\n Village House\n",HKD$5.68 Millions,NaN,"\n ,\n \n \n\n ,\n ,Village House,Mountain view,Elegant,Outdoor Car Park,Balcony,RoofTop,MTR nearby,Flame Cooking"
5876,"\n (Gross: 700 ft²), 3 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-13392,"\n Sai Kung\n ,\n Village\n",HKD$6.98 Millions,NaN,"\n ,\n \n \n\n ,\n ,Village House,Elegant,Garden"
5877,"\n (Gross: 700 ft²), 3 beds , 2 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-14074,"\n Clear Water Bay\n ,\n Village House\n",HKD$6.3 Millions,NaN,"\n ,\n \n \n\n ,\n ,Village House,Elegant,Garden,Ensuite"
6143,"\n (Gross: 1,014 ft²) \n",https://www.squarefoot.com.hk/buy/residential/property-30193,"\n Tai Po\n ,\n The Horizon\n",HKD$18.99 Millions,NaN,"\n ,\n \n \n\n ,\n ,Apartment,Garden,\n"

In [704]:
list_of_tags_sf = []
for i in squarefoot['tags']:
    helper = re.sub("\s\s+" , " ",i)
    helper = helper.split(',')
    helper = [x.strip() for x in helper]
    j = 0 
    helper_pop = []
    for j in range(0,len(helper)):
        if helper[j] == '':
            helper_pop.append(j)
    for i in sorted(helper_pop,reverse=True):
        del helper[i]
    list_of_tags_sf.append(helper)

In [705]:
list_of_tags_sf_unique=[]
for i in list_of_tags_sf:
    for j in i:
        list_of_tags_sf_unique.append(j)

In [709]:
sf_tags = ['Western Style Bldg',
 'Mountain view',
 'Garden',
 'Outdoor Car Park',
 'Sea view',
 'Luxury',
 'MTR nearby',
 'Balcony',
 'Terrace',
 'City view',
 'Simple',
 'Indoor Car Park',
 'Good view',
 'Elegant',
 'Garden view',
 'River view',
 'Duplex Apartment',
 'Club House',
 'Building view',
 'Shopping Mall nearby',
 'RoofTop']
for i in sf_tags:
    squarefoot[i]=''

In [710]:
counter = 0 
for i in list_of_tags_sf:
    for key in i:
        squarefoot.loc[counter,key] = 1
    counter += 1

In [711]:
squarefoot = squarefoot.drop(columns = ['Apartment', 'Good school zone',
       'Ensuite', 'House', '1', 'Sole Agent', 'Maid bedroom', 'Village House',
       'Flame Cooking', 'Stand-alone Building', 'Whole floor',
       'Free in Market', 'Home Ownership', 'VR', 'Premium Unpaid',
       'type_name_eng', 'Tong Lau', 'Sold', 'landlord', 'Public Housing',"Welcome University's Student",
        'With tenant agreement'])

In [712]:
list_of_area_sf = []
for i in squarefoot['area']:
    helper = re.sub("\s\s+" , " ",i)
    helper = helper.split(', ')
    helper = [x.strip() for x in helper]
    j = 0 
    helper_pop = []
    for j in range(0,len(helper)):
        if helper[j] == '':
            helper_pop.append(j)
    for i in sorted(helper_pop,reverse=True):
        del helper[i]
    list_of_area_sf .append(helper)

In [715]:
squarefoot['area_V2'] = ''
squarefoot['bedroom'] = ''
squarefoot['bathrooms'] = ''

In [717]:
counter = 0
for i in list_of_area_sf:
    if i[0].startswith('(Gross'):
        i = i[0].split(':')
        squarefoot.loc[counter,'area_V2'] = i[1]
    else:
        try:
            squarefoot.loc[counter,'area_V2'] = i[0]
        except:
            pass
        try:
            squarefoot.loc[counter,'bedroom'] = i[1]
        except:
            pass
    counter += 1

In [718]:
list_of_location_sf = []
for i in squarefoot['location']:
    helper = re.sub("\s\s+" , " ",i)
    helper = helper.split(',')
    helper = [x.strip() for x in helper]
    j = 0 
    helper_pop = []
    for j in range(0,len(helper)):
        if helper[j] == '':
            helper_pop.append(j)
    for i in sorted(helper_pop,reverse=True):
        del helper[i]
    list_of_location_sf.append(helper)

In [720]:
squarefoot['district'] = ''
squarefoot['building'] = ''
counter = 0
for i in list_of_location_sf:
    try:
        squarefoot.loc[counter,'district'] = i[0]
    except:
        pass
    try:
        squarefoot.loc[counter,'building'] = i[1]
    except:
        pass
    counter += 1

In [722]:
squarefoot

,area,link,location,price,price_per,tags,Western Style Bldg,Mountain view,Garden,Outdoor Car Park,Sea view,Luxury,MTR nearby,Balcony,Terrace,City view,Simple,Indoor Car Park,Good view,Elegant,Garden view,River view,Duplex Apartment,Club House,Building view,Shopping Mall nearby,RoofTop,area_V2,bedroom,bathrooms,district,building
0,"\n 503 ft², 2 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-32773,"\n Ma On Shan\n ,\n Double Cove\n",HKD$7.4 Millions,"@14,712","\n ,\n ,\n ,\n",,,,,,,,,,,,,,,,,,,,,,503 ft²,2 beds,,Ma On Shan,Double Cove
1,"\n 1,039 ft² (Gross: 1,206 ft²), 3 beds , 2 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-32758,"\n Fotan\n ,\n Royal Ascot\n",HKD$12.95 Millions,"@12,464","\n ,\n ,\n ,\n ,\n",,,,,,,,,,,,,,,,,,,,,,"1,039 ft² (Gross: 1,206 ft²)",3 beds,,Fotan,Royal Ascot
2,"\n 857 ft², 3 beds , 2 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-32754,"\n ShaTin\n ,\n Peak One\n",HKD$15.5 Millions,"@18,086","\n ,\n ,\n",,,,,,,,,,,,,,,,,,,,,,857 ft²,3 beds,,ShaTin,Peak One
3,"\n 743 ft², 3 beds , 2 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-32752,"\n Tai Wai\n ,\n The Riverpark\n",HKD$14.6 Millions,"@19,650","\n ,\n ,\n ,\n",,,,,,,,,,,,,,,,,,,,,,743 ft²,3 beds,,Tai Wai,The Riverpark
4,"\n 498 ft², 2 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-32745,"\n Tai Po\n ,\n St MARTIN\n",HKD$9.2 Millions +,"@18,474","\n ,\n ,\n ,\n ,\n",,,,,,,,,,,,,,,,,,,,,,498 ft²,2 beds,,Tai Po,St MARTIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6187,"\n 511 ft², 1 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-14508,"\n Western mid-levels\n ,\n Bel Mount Garden\n",HKD$13 Millions,"@25,440","\n ,\n \n \n\n ,\n ,Apartment,Garden view,City view,Elegant,Balcony,MTR nearby",,,,,,,1,1,,1,,,,1,1,,,,,,,511 ft²,1 beds,,Western mid-levels,Bel Mount Garden
6188,"\n 398 ft² (Gross: 520 ft²), 2 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-31838,"\n Quarry Bay\n ,\n WestLands Court\n",HKD$7.08 Millions,"@17,789","\n ,\n \n \n\n ,\n ,Apartment,Good view,Shopping Mall nearby,MTR nearby",,,,,,,1,,,,,,1,,,,,,,1,,398 ft² (Gross: 520 ft²),2 beds,,Quarry Bay,WestLands Court
6189,"\n 391 ft² (Gross: 474 ft²), 2 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-31837,"\n Quarry Bay\n ,\n Nan Fung Sun Chuen\n",HKD$6.2 Millions,"@15,857","\n ,\n \n \n\n ,\n ,Apartment,Shopping Mall nearby,MTR nearby,Good view",,,,,,,1,,,,,,1,,,,,,,1,,391 ft² (Gross: 474 ft²),2 beds,,Quarry Bay,Nan Fung Sun Chuen
6190,"\n 935 ft², 3 beds , 2 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-31827,"\n North Point Mid\n ,\n Sky Horizon\n",HKD$30.8 Millions,"@32,941","\n ,\n \n \n\n ,\n ,Apartment,Good view,Sea view,Elegant",,,,,1,,,,,,,,1,1,,,,,,,,935 ft²,3 beds,,North Point Mid,Sky Horizon
6191,"\n 530 ft² (Gross: 738 ft²), 2 beds , 1 bathrooms\n",https://www.squarefoot.com.hk/buy/residential/property-19696,"\n Tung Chung\n ,\n Seaview Crescent\n",HKD$7.55 Millions,"@14,245","\n ,\n \n \n\n ,\n ,Apartment,Mountain view,Good view",,1,,,,,,,,,,,1,,,,,,,,,530 ft² (Gross: 738 ft²),2 beds,,Tung Chung,Seaview Crescent

In [723]:
squarefoot.columns

Index(['area', 'link', 'location', 'price', 'price_per', 'tags',
       'Western Style Bldg', 'Mountain view', 'Garden', 'Outdoor Car Park',
       'Sea view', 'Luxury', 'MTR nearby', 'Balcony', 'Terrace', 'City view',
       'Simple', 'Indoor Car Park', 'Good view', 'Elegant', 'Garden view',
       'River view', 'Duplex Apartment', 'Club House', 'Building view',
       'Shopping Mall nearby', 'RoofTop', 'area_V2', 'bedroom', 'bathrooms',
       'district', 'building'],
      dtype='object')

In [724]:
squarefoot['floor_level'] = ''
squarefoot['car_parking'] = ''
squarefoot['Lux_Revo'] = ''

In [725]:
def squarefoot_floor(listV2,column,value):
    counter = 0
    for i in squarefoot[listV2]:
        if i ==1:
            squarefoot.loc[counter,column] = value
        counter += 1

In [726]:
for i in ['Good view','City view','River view','Mountain view']:
    squarefoot_floor(i,'floor_level','H')
squarefoot=squarefoot.drop(columns=['Good view','City view','River view','Mountain view'])

In [727]:
for i in ['Outdoor Car Park','Indoor Car Park']:
    squarefoot_floor(i,'car_parking',1)
squarefoot=squarefoot.drop(columns=['Outdoor Car Park','Indoor Car Park'])

In [728]:
for i in ['Luxury','Elegant']:
    squarefoot_floor(i,'Lux_Revo',1)
squarefoot= squarefoot.drop(columns=['Luxury','Elegant'])

In [729]:
for i in range(0,len(squarefoot.area_V2)):
    squarefoot.loc[i,'area_V2'] = squarefoot.area_V2[i].split()[0]
    try:
        squarefoot.loc[i,'bedroom'] = squarefoot.bedroom[i].split()[0]
    except:
        pass

In [730]:
squarefoot=squarefoot.drop(columns = ['area','tags','location','Western Style Bldg'])

In [731]:
squarefoot= squarefoot.drop(columns=['Building view','Duplex Apartment','Garden','Simple','bathrooms'])

In [732]:
squarefoot= squarefoot.drop(squarefoot[squarefoot.link=='link'].index)

In [733]:
squarefoot['Mountain View'] = ''
squarefoot['River View'] = ''
squarefoot['Swimming'] = ''
squarefoot = squarefoot.rename(columns={'district':'location','area_V2':'net_area','bedroom':'bedroom_amount',
                                       'Sea view':'Sea View','Garden view':'Garden View','RoofTop':'Rooftop'})

In [734]:
squarefoot['price'] = squarefoot['price'].str.extract("(\d*\.?\d+)", expand=True)
squarefoot['price'] = pd.to_numeric(squarefoot['price'])

In [735]:
helper_list = []
for i in squarefoot['net_area']:
    helper_list.append(i.replace(',', ''))
helper_list = pd.to_numeric(helper_list)
squarefoot['net_area']=helper_list

In [736]:
squarefoot['price'] = squarefoot['price'].apply(lambda x: x*1000000)

In [737]:
squarefoot['price_per'] = round(squarefoot['price']/squarefoot['net_area'])

In [ ]:
squarefoot['address'] = list_address

In [878]:
squarefoot = squarefoot.reindex(sorted(squarefoot.columns), axis=1)

In [879]:
display(Mid_life.head(1),hkp_data.head(1),squarefoot.head(1))

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,address,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
0,,,1,,,,,,,1,,,2 Tai Wing Avenue,1.0,,,H,https://www.midland.com.hk/en/property/Hong-Kong-Island-Taikoo-Taikoo-Shing-Kwun-Hoi-Terrace-Nam-Hoi-Mansion-Higher-Floor-Flat-H-M150085930,Sai Wan Ho,552,11500000,20833.0

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,address,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
0,1,1,,,,,,,,,1,,89 Pok Fu Lam Road,2.0,,,H,https://www.hkp.com.hk/en/property/Hong-Kong-Island-Hong-Kong-West-The-Belcher-s-Phase-1-Block-1-High-Floor-Flat-B-H100203780,Hong Kong West,766,20200000,26371.0

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,address,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
0,,,,,,,,,,,,,No.8 Wu Kai Sha Road,2,Double Cove,,,https://www.squarefoot.com.hk/buy/residential/property-32773,Ma On Shan,503,7400000.0,14712.0

# Mid Life

In [893]:
Mid_life_hkp = pd.concat([hkp_data,Mid_life],ignore_index=True)
Mid_life_hkp.tail(2)

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,address,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
10789,1,,,,,,,,,,1,,8 Wu Kai Sha Road,3.0,,,H,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-1-Block-5-Higher-Floor-Flat-D-M301184734,Ma On Shan,799,14280000,17872.0
10790,,,,,,,,,,,,,8 Wu Kai Sha Road,1.0,,,M,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-3-Double-Cove-Starview-Prime-Block-16-Middle-Floor-Flat-F-M300267793,Ma On Shan,473,8600000,18182.0

In [894]:
squareMidhkp = pd.concat([squarefoot,Mid_life_hkp],ignore_index = True)

In [900]:
squareMidhkp=squareMidhkp.drop(squareMidhkp[squareMidhkp.link=='link'].index)
squareMidhkp=squareMidhkp.drop(squareMidhkp[squareMidhkp.price==0].index)
squareMidhkp=squareMidhkp.drop(squareMidhkp[squareMidhkp.net_area==0].index)

In [901]:
squareMidhkp

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,address,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
0,,,,,,,,,,,,,No.8 Wu Kai Sha Road,2,Double Cove,,,https://www.squarefoot.com.hk/buy/residential/property-32773,Ma On Shan,503,7400000.0,14712.0
1,,,,,,,,,,,,,Middle Floor,3,Royal Ascot,,,https://www.squarefoot.com.hk/buy/residential/property-32758,Fotan,1039,12950000.0,12464.0
2,,,,,,,,,,,,,No. 63 Mei Tin Road,3,Peak One,,,https://www.squarefoot.com.hk/buy/residential/property-32754,ShaTin,857,15500000.0,18086.0
3,,,,,,,,,,,,,No.8 Che Kung Miu Road,3,The Riverpark,,,https://www.squarefoot.com.hk/buy/residential/property-32752,Tai Wai,743,14600000.0,19650.0
4,,,,,,,,,,,,,No.12 Fo Chun Road,2,St MARTIN,,,https://www.squarefoot.com.hk/buy/residential/property-32745,Tai Po,498,9200000.0,18474.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16976,1,1,,,,,,,,,1,,8 Yuen Lung Street,2.0,,,L,https://www.midland.com.hk/en/property/New-Territories-Yuen-Long-Town-Centre-Yoho-Town-Phase-1-Block-7-Lower-Floor-Flat-E-M300322350,Yuen Long,423,7800000.0,18440.0
16977,,,,,,,,,,1,,,8 Wu Kai Sha Road,1.0,,,M,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-1-Block-2-Middle-Floor-Flat-B-M300383999,Ma On Shan,482,8600000.0,17842.0
16978,1,1,,,1,,,,,,1,,398 Castle Peak Road Tsuen Wan,2.0,,,M,https://www.midland.com.hk/en/property/New-Territories-Tsuen-Wan-Town-Centre-Discovery-Park-Phase-1-Block-03-Middle-Floor-Flat-C-M300516409,Tsuen Wan,495,7700000.0,15556.0
16979,1,,,,,,,,,,1,,8 Wu Kai Sha Road,3.0,,,H,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-1-Block-5-Higher-Floor-Flat-D-M301184734,Ma On Shan,799,14280000.0,17872.0
16980,,,,,,,,,,,,,8 Wu Kai Sha Road,1.0,,,M,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-3-Double-Cove-Starview-Prime-Block-16-Middle-Floor-Flat-F-M300267793,Ma On Shan,473,8600000.0,18182.0

In [897]:
squareMidhkp.to_csv('squareMidhkp_data_final.csv')

In [613]:
a = squareMidhkp.groupby('location',as_index=False)['price_per'].mean().sort_values('price_per')
a[a.location=='Tai Wai']

   location     price_per
88  Tai Wai  19699.636364

In [618]:
squareMidhkp[squareMidhkp.location =='Tai Wai'].sort_values('price')

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
6085,,,,1,,,,,,,,,1,May Shing Court,,H,https://www.squarefoot.com.hk/buy/residential/property-30038,Tai Wai,363,4880000.0,13444.0
5643,,,1,,,,,,,,,,,The Riverpark,,,https://www.squarefoot.com.hk/buy/residential/property-32553,Tai Wai,508,10280000.0,20236.0
309,,,,1,,,,,,,,,2,The Riverpark,,,https://www.squarefoot.com.hk/buy/residential/property-32152,Tai Wai,507,10300000.0,20316.0
5589,,,1,,,,,,,,,,,The Riverpark,,,https://www.squarefoot.com.hk/buy/residential/property-32504,Tai Wai,507,10380000.0,20473.0
5440,1,1,,1,1,,,,,1,,,2,The Riverpark,,H,https://www.squarefoot.com.hk/buy/residential/property-32278,Tai Wai,508,10680000.0,21024.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5594,,,,1,,,,,,,,,5+,Hill Paramount,1,,https://www.squarefoot.com.hk/buy/residential/property-32482,Tai Wai,3552,98000000.0,27590.0
427,,,1,,,,,1,,,,1,5+,Hill Paramount,1,H,https://www.squarefoot.com.hk/buy/residential/property-29608,Tai Wai,3552,98000000.0,27590.0
4106,,,,1,1,,,,,,,,4,Godi,,H,https://www.squarefoot.com.hk/buy/residential/property-29399,Tai Wai,3613,140000000.0,38749.0
4549,,,,,,,,,,,,,,Godi,,,https://www.squarefoot.com.hk/buy/residential/property-30080,Tai Wai,3613,159990000.0,44282.0
5602,,,,1,,,,,,,,,4,Godi,,,https://www.squarefoot.com.hk/buy/residential/property-32477,Tai Wai,3613,160000000.0,44285.0

In [898]:
Mid_life

,Balcony,Club House,Garden View,Lux_Revo,MTR nearby,Mountain View,River View,Rooftop,Sea View,Shopping Mall nearby,Swimming,Terrace,address,bedroom_amount,building,car_parking,floor_level,link,location,net_area,price,price_per
0,,,1,,,,,,,1,,,2 Tai Wing Avenue,1.0,,,H,https://www.midland.com.hk/en/property/Hong-Kong-Island-Taikoo-Taikoo-Shing-Kwun-Hoi-Terrace-Nam-Hoi-Mansion-Higher-Floor-Flat-H-M150085930,Sai Wan Ho,552,11500000,20833.0
1,,,,,,1,,,,1,,,9 Tong Tak Street,2.0,,,M,https://www.midland.com.hk/en/property/Kowloon-Tseung-Kwan-O-Town-Centre-Park-Central-Phase-2-Block-03-Middle-Floor-Flat-D-M250591554,Tseung Kwan O Station,465,8300000,17849.0
2,1,,1,,,,,,,1,,,8 Yan King Road,2.0,,,M,https://www.midland.com.hk/en/property/Kowloon-Po-Lam-Metro-City-Phase-2-Block-08-Middle-Floor-Flat-C-M200441423,Tseung Kwan O Station,363,6800000,18733.0
3,,,1,,,,,,,1,,,22 Taikoo Wan Road,3.0,,,H,https://www.midland.com.hk/en/property/Hong-Kong-Island-Taikoo-Taikoo-Shing-Harbour-View-Gardens-West-Willow-Mansion-Higher-Floor-Flat-E-M150163070,Sai Wan Ho,922,19200000,20824.0
4,1,1,,,,,,,,1,1,,8 Yan King Road,2.0,,,M,https://www.midland.com.hk/en/property/Kowloon-Po-Lam-Metro-City-Phase-2-Block-11-Middle-Floor-Flat-B-M200438082,Tseung Kwan O Station,363,6880000,18953.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,1,1,,,,,,,,,1,,8 Yuen Lung Street,2.0,,,L,https://www.midland.com.hk/en/property/New-Territories-Yuen-Long-Town-Centre-Yoho-Town-Phase-1-Block-7-Lower-Floor-Flat-E-M300322350,Yuen Long,423,7800000,18440.0
887,,,,,,,,,,1,,,8 Wu Kai Sha Road,1.0,,,M,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-1-Block-2-Middle-Floor-Flat-B-M300383999,Ma On Shan,482,8600000,17842.0
888,1,1,,,1,,,,,,1,,398 Castle Peak Road Tsuen Wan,2.0,,,M,https://www.midland.com.hk/en/property/New-Territories-Tsuen-Wan-Town-Centre-Discovery-Park-Phase-1-Block-03-Middle-Floor-Flat-C-M300516409,Tsuen Wan,495,7700000,15556.0
889,1,,,,,,,,,,1,,8 Wu Kai Sha Road,3.0,,,H,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-1-Block-5-Higher-Floor-Flat-D-M301184734,Ma On Shan,799,14280000,17872.0
890,,,,,,,,,,,,,8 Wu Kai Sha Road,1.0,,,M,https://www.midland.com.hk/en/property/New-Territories-Wu-Kai-Sha-Double-Cove-Phase-3-Double-Cove-Starview-Prime-Block-16-Middle-Floor-Flat-F-M300267793,Ma On Shan,473,8600000,18182.0

# WIKIINFO

In [994]:
driver = webdriver.Chrome(ChromeDriverManager().install())
url = 'https://en.wikipedia.org/wiki/List_of_places_in_Hong_Kong#Hong_Kong_Island'
driver.get(url)
location_list = []
for i in [11,13,15]:
    if i == 11:
        for j in range(1,5):
            a = driver.find_element(By.CSS_SELECTOR,'#mw-content-text > div.mw-parser-output > ul:nth-child('+str(i)+') > li:nth-child('+str(j)+')')
            district = a.text.split('\n')[0]
            area = a.text.split('\n')[1:]
            info = {'district':district,'area':area}
            location_list.append(info)

hongkong_island = pd.DataFrame(location_list)
helper_list = []
for i in hongkong_island.district:
    helper = hongkong_island[hongkong_island.district==i]
    for j in helper.area.tolist()[0]:
        location = {'district':i,'area':j}
        helper_list.append(location)
hongkong_island = pd.DataFrame(helper_list)
hongkong_island['region'] = 'Hong Kong Island'
hongkong_island

/var/folders/3j/z8kbfz2n3m59k30tjntx27xc0000gn/T/ipykernel_67054/3701218224.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

                        district                    area            region
0   Central and Western District        Central District  Hong Kong Island
1   Central and Western District               Admiralty  Hong Kong Island
2   Central and Western District              Mid-Levels  Hong Kong Island
3   Central and Western District                    Soho  Hong Kong Island
4   Central and Western District                 Sai Wan  Hong Kong Island
5   Central and Western District            Kennedy Town  Hong Kong Island
6   Central and Western District            Sai Ying Pun  Hong Kong Island
7   Central and Western District          Shek Tong Tsui  Hong Kong Island
8   Central and Western District              Sheung Wan  Hong Kong Island
9               Eastern District                Chai Wan  Hong Kong Island
10              Eastern District             North Point  Hong Kong Island
11              Eastern District            Braemar Hill  Hong Kong Island
12              Eastern District           Fortress Hill  Hong Kong Island
13              Eastern District  North Point Mid-Levels  Hong Kong Island
14              Eastern District              Quarry Bay  Hong Kong Island
15              Eastern District                Kornhill  Hong Kong Island
16              Eastern District            Taikoo Shing  Hong Kong Island
17              Eastern District              Sai Wan Ho  Hong Kong Island
18              Eastern District            Shau Kei Wan  Hong Kong Island
19              Eastern District           Heng Fa Chuen  Hong Kong Island
20              Eastern District             Aldrich Bay  Hong Kong Island
21              Eastern District             A Kung Ngam  Hong Kong Island
22             Southern District                Aberdeen  Hong Kong Island
23             Southern District             Ap Lei Chau  Hong Kong Island
24             Southern District           Chung Hom Kok  Hong Kong Island
25             Southern District             Siu Sai Wan  Hong Kong Island
26             Southern District               Cyberport  Hong Kong Island
27             Southern District           Telegraph Bay  Hong Kong Island
28             Southern District          Deep Water Bay  Hong Kong Island
29             Southern District              Pok Fu Lam  Hong Kong Island
30             Southern District               Sandy Bay  Hong Kong Island
31             Southern District               Shan Ting  Hong Kong Island
32             Southern District                  Wah Fu  Hong Kong Island
33             Southern District                 Tin Wan  Hong Kong Island
34             Southern District             Repulse Bay  Hong Kong Island
35             Southern District                 Stanley  Hong Kong Island
36             Southern District                  Shek O  Hong Kong Island
37             Southern District            Big Wave Bay  Hong Kong Island
38             Southern District                 Tai Tam  Hong Kong Island
39             Southern District          Wong Chuk Hang  Hong Kong Island
40             Southern District           Nam Long Shan  Hong Kong Island
41             Southern District              Ocean Park  Hong Kong Island
42             Wan Chai District            Causeway Bay  Hong Kong Island
43             Wan Chai District                 Tin Hau  Hong Kong Island
44             Wan Chai District           Caroline Hill  Hong Kong Island
45             Wan Chai District            Happy Valley  Hong Kong Island
46             Wan Chai District       Jardine's Lookout  Hong Kong Island
47             Wan Chai District                Tai Hang  Hong Kong Island
48             Wan Chai District                Wan Chai  Hong Kong Island

In [ ]:
driver = webdriver.Chrome(ChromeDriverManager().install())
url = 'https://en.wikipedia.org/wiki/List_of_places_in_Hong_Kong#Hong_Kong_Island'
driver.get(url)
location_list = []
for i in [11,13,15]:
    if i == 11:
        for j in range(1,5):
            a = driver.find_element(By.CSS_SELECTOR,'#mw-content-text > div.mw-parser-output > ul:nth-child('+str(i)+') > li:nth-child('+str(j)+')')
            district = a.text.split('\n')[0]
            area = a.text.split('\n')[1:]
            info = {'district':district,'area':area}
            location_list.append(info)

hongkong_island = pd.DataFrame(location_list)
helper_list = []
for i in hongkong_island.district:
    helper = hongkong_island[hongkong_island.district==i]
    for j in helper.area.tolist()[0]:
        location = {'district':i,'area':j}
        helper_list.append(location)
hongkong_island = pd.DataFrame(helper_list)
hongkong_island['region'] = 'Hong Kong Island'
hongkong_island

In [995]:
driver = webdriver.Chrome(ChromeDriverManager().install())
url = 'https://en.wikipedia.org/wiki/List_of_places_in_Hong_Kong#Hong_Kong_Island'
driver.get(url)
location_list = []
for i in [11,13,15]:
    if i == 13:
        for j in range(1,6):
            a = driver.find_element(By.CSS_SELECTOR,'#mw-content-text > div.mw-parser-output > ul:nth-child('+str(i)+') > li:nth-child('+str(j)+')')
            district = a.text.split('\n')[0]
            area = a.text.split('\n')[1:]
            info = {'district':district,'area':area}
            location_list.append(info)
            location_list.append(info)

kowloon = pd.DataFrame(location_list)
helper_list = []
for i in kowloon.district:
    helper = kowloon[kowloon.district==i]
    for j in helper.area.tolist()[0]:
        location = {'district':i,'area':j}
        helper_list.append(location)
kowloon = pd.DataFrame(helper_list)
kowloon['region'] = 'Kowloon'
kowloon

/var/folders/3j/z8kbfz2n3m59k30tjntx27xc0000gn/T/ipykernel_67054/1391758670.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

                   district                area   region
0     Kowloon City District          Ho Man Tin  Kowloon
1     Kowloon City District            Hung Hom  Kowloon
2     Kowloon City District      Whampoa Garden  Kowloon
3     Kowloon City District        Kowloon City  Kowloon
4     Kowloon City District        Kowloon Tong  Kowloon
..                      ...                 ...      ...
109  Yau Tsim Mong District        Tai Kok Tsui  Kowloon
110  Yau Tsim Mong District       Tsim Sha Tsui  Kowloon
111  Yau Tsim Mong District  Tsim Sha Tsui East  Kowloon
112  Yau Tsim Mong District          Yau Ma Tei  Kowloon
113  Yau Tsim Mong District              Jordan  Kowloon

[114 rows x 3 columns]

In [996]:
driver = webdriver.Chrome(ChromeDriverManager().install())
url = 'https://en.wikipedia.org/wiki/List_of_places_in_Hong_Kong#Hong_Kong_Island'
driver.get(url)
location_list = []
for i in [11,13,15]:
    if i == 15:
        for j in range(1,10):
            a = driver.find_element(By.CSS_SELECTOR,'#mw-content-text > div.mw-parser-output > ul:nth-child('+str(i)+') > li:nth-child('+str(j)+')')
            district = a.text.split('\n')[0]
            area = a.text.split('\n')[1:]
            info = {'district':district,'area':area}
            location_list.append(info)

new = pd.DataFrame(location_list)
helper_list = []
for i in new.district:
    helper = new[new.district==i]
    for j in helper.area.tolist()[0]:
        location = {'district':i,'area':j}
        helper_list.append(location)
new = pd.DataFrame(helper_list)
new['region'] = 'New Territories'
new

/var/folders/3j/z8kbfz2n3m59k30tjntx27xc0000gn/T/ipykernel_67054/1181716322.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

               district                      area           region
0      Islands District              Chek Lap Kok  New Territories
1      Islands District               Cheung Chau  New Territories
2      Islands District              Lamma Island  New Territories
3      Islands District            Hung Shing Yeh  New Territories
4      Islands District               Lo So Shing  New Territories
..                  ...                       ...              ...
141  Yuen Long District            Shap Pat Heung  New Territories
142  Yuen Long District                  Tai Tong  New Territories
143  Yuen Long District            Yuen Long Town  New Territories
144  Yuen Long District          Long Ping Estate  New Territories
145  Yuen Long District  King's Road, North Point  New Territories

[146 rows x 3 columns]

In [1001]:
combined_district = pd.concat([hongkong_island,kowloon,new],ignore_index=True)

In [1003]:
combined_district.to_csv('combined_district.csv')

In [1010]:
combined_district[combined_district.area=='Discovery Bay']

             district           area           region
176  Islands District  Discovery Bay  New Territories

'Soho'